Stop trying to use environment variables in config
They don't work with ExtendedInterpolation. I don't know how we ever
thought they were okay.

For example, chainging sbws_home from ~/.sbws to $HOME/.sbws

(venv-test) matt@spacecow:~/src/simple-bw-scanner$ sbws scanner
Traceback (most recent call last):
  File "/home/matt/src/simple-bw-scanner/venv-test/bin/sbws", line 11, in <module>
    sys.exit(main())
  File "/home/matt/src/simple-bw-scanner/venv-test/lib/python3.5/site-packages/sbws/sbws.py", line 46, in main
    _ensure_dirs(conf)
  File "/home/matt/src/simple-bw-scanner/venv-test/lib/python3.5/site-packages/sbws/sbws.py", line 24, in _ensure_dirs
    os.makedirs(conf.getpath('paths', 'datadir'), exist_ok=True)
  File "/usr/lib/python3.5/configparser.py", line 806, in _get_conv
    **kwargs)
  File "/usr/lib/python3.5/configparser.py", line 800, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.5/configparser.py", line 797, in get
    d)
  File "/usr/lib/python3.5/configparser.py", line 454, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.5/configparser.py", line 510, in _interpolate_some
    depth + 1)
  File "/usr/lib/python3.5/configparser.py", line 517, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '$' must be followed by '$' or '{', found: '$HOME/.sbws'

This commit changes Tor's run_dpath from $XDG_RUNTIME_DIR/sbws to
${tor:datadir}/run (which is ~/.sbws/tor/run by default)